# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Reads a single row of JSON and returns a data frame with one row
#'
#' @name fjson_parse_string
#'
#' @param string A single string.
#' @export
fjson_parse_string <- function(string) {
    .Call('_fjson_fjson_parse_string', PACKAGE = 'fjson', string)
}

#' Reads multiple rows of JSON and returns a list of data frames
#'
#' @name fjson_parse_vector
#'
#' @param strings A vector of strings.
#' @export
fjson_parse_vector <- function(strings) {
    .Call('_fjson_fjson_parse_vector', PACKAGE = 'fjson', strings)
}

